version: "3"
services:
  ebanking-app:
    container_name: ebanking-docker
    image: ebanking-app
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://containers-us-west-65.railway.app:5698/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0egsHaid8d32aMwUyhdY
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.28
#    volumes:
#      -  /dockerdata/mysql:/var/lib/mysql
    ports:
      - 3307:5698
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: root